function                                                                     ...
generateKinematicsSolutionsUsageMessage(  )
%{------------------------------------------------------------------------------
   STDOUT = 1;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   fprintf                                                                   ...
   (                                                                         ...
     STDOUT,                                                                 ...
     [                                                                       ...
       '\n\n\n'                                                              ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%'                                           ...
       '%s%s\n'                                                              ...
       '\n\n\n'                                                              ...
     ],                                                                      ...
     '====================================================================', ...
     '===========',                                                          ...
     '|',                                                                    ...
     '|  USAGE:',                                                            ...
     '|',                                                                    ...
     '|    [                                                        ...',    ...
     '|      actualSimulationTimes,                                 ...',    ...
     '|      rotationVectorsInertialCoords,                         ...',    ...
     '|      angularVelocitiesBodyCoords                            ...',    ...
     '|    ] = generateSolutionsForFreeRotationRigidBodyKinematics  ...',    ...
     '|                (                                            ...',    ...
     '|                  J,                                         ...',    ...
     '|                  initialRotationVector,                     ...',    ...
     '|                  intitalAngularVelocity                     ...',    ...
     '|                  numberTimeSamples,                         ...',    ...
     '|                  simulationEndTime                          ...',    ...
     '|                );',                                                  ...
     '|',                                                                    ...
     '====================================================================', ...
     '==========='                                                           ...
   );
%------------------------------------------------------------------------------- 
   return;
%}------------------------------------------------------------------------------
