function                                                                     ...
generateFreeUnstableRigidBodyRotationDemoPurposeMessage(  )
%{------------------------------------------------------------------------------
   STDOUT = 1;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   fprintf                                                                   ...
   (                                                                         ...
     STDOUT,                                                                 ...
     [                                                                       ...
       '\n\n\n'                                                              ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n'                                            ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n'                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n'                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n'                                                ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                                    ...
       '%s%s\n'                                                              ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                            ...
       '%s%s\n'                                                              ...
       '\n\n\n'                                                              ...
     ],                                                                      ...
     '====================================================================', ...
     '===========',                                                          ...
     '|',                                                                    ...
     '|  PURPOSE:',                                                          ...
     '|',                                                                    ...
     '|    Perform a deomonstration of free unstable rotation of a',         ...
     '|    rigid body.',                                                     ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  INPUT(s):',                                                         ...
     '|',                                                                    ...
     '|    None',                                                            ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  OUTPUT(s):',                                                        ...
     '|',                                                                    ...
     '|     None',                                                           ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  RETURN VALUE(s):',                                                  ...
     '|',                                                                    ...
     '|     None.',                                                          ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  NOTE(s):',                                                          ...
     '|',                                                                    ...
     '|    [ 1 ]  Rotating object kinematics is "rotation vector" based.',   ...
     '|',                                                                    ...
     '|    [ 2 ] Rotation Vector Definition:',                               ...
     '|',                                                                    ...
     '|          A rotation vector is a one dimensional row or',             ...
     '|          column vector of length three.',                            ...
     '|',                                                                    ...
     '|            [ 2.1 ] The norm of the rotation vector is the rotation', ...
     '|                    angle.',                                          ...
     '|',                                                                    ...
     '|            [ 2.2 ] The normalized rotation vector is a 3D unit',     ...
     '|                    vector which serves as the rotation axis.',       ...
     '|',                                                                    ...
     '|    [ 3 ]  Ordinary Differential Equations (ODEs) are solved using',  ...
     '|           the Matlab "ode45" function to apply the',                 ...
     '|           Dorman-Prince 4(5) explicit embedded variable time',       ...
     '|           step Runge-Kutta method.',                                 ...
     '|',                                                                    ...
     '|    [ 4 ] State Vector Components:',                                  ...
     '|',                                                                    ...
     '|          [ 4.1 ]  State Vector components 1, 2 and 3 are the',       ...
     '|                   "rotation vector".',                               ...
     '|',                                                                    ...
     '|          [ 4.2 ]  State Vector components 4, 5 and 6 are the',       ...
     '|                   angular velocity vector.',                         ...
     '|',                                                                    ...
     '|    [ 5 ] Time rate of change of the rotation vector:',               ...
     '|',                                                                    ...
     '|          [ 5.1 ] The time rate of change of the rotation vector',    ...
     '|                  is not the angular velocity vector.',               ...
     '|',                                                                    ...
     '|          [ 5.2 ] To determine the time rate of change of the',       ...
     '|                  rotation vector, use Equation (42) on Page 265',    ...
     '|                  of Reference [ 1 ].',                               ...
     '|',                                                                    ...
     '|-------------------------------------------------------------------', ...
     '-----------',                                                          ...
     '|',                                                                    ...
     '|  REFERENCE(s):',                                                     ...
     '|',                                                                    ...
     '|    [ 1 ]  "The Kinematic Equation for the Rotation Vector",',        ...
     '|           Malcolm D. Shuster,',                                      ...
     '|           IEEE Transactions on Aerospace and Electronic Systems,',   ...
     '|           Vol. 29, No. 1, pp. 263 - 267,',                           ...
     '|           January 1993',                                             ...
     '|           malcolmdshuster.com/Pub_1993c_J_RotVec_IEEE.pdf',          ...
     '|',                                                                    ...
     '|    [ 2 ]  "A Survey of Attitude Representations",',                  ...
     '|           Malcolm D. Shuster,',                                      ...
     '|           The Journal of the Astronautical Sciences,',               ...
     '|           Vol. 41, No. 4, pp. 430 - 517,',                           ...
     '|           October-December, 1993',                                   ...
     '|           malcolmdshuster.com/Pub_1993h_J_Repsurv_scan.pdf',         ...
     '|',                                                                    ...
     '|    [ 3 ]  "The Bizarre Behavior of Rotating Bodies -',               ...
     '|            The Dzhanibekov Effect",',                                ...
     '|            Derek Alexander Muller',                                  ...
     '|            YouTube channel Veritasium',                              ...
     '|            Spinning objects have strange instabilities known as',    ...
     '|            "The Dzhanibekov Effect" or "Tennis Racket Theorem" -',   ...
     '|            this video offers an intuitive explanation.',             ...
     '|            https://www.youtube.com/watch?v=1VPfZ_XzisU',             ...
     '|',                                                                    ...
     '|    [ 4 ]  Elements of the following were used to help create',       ...
     '|           this project:',                                            ...
     '|',                                                                    ...
     '|           [ 4.1 ]  https://github.com/alaricgregoire/EulerFreeBody', ...
     '|                    www.mathworks.com/matlabcentral/fileexchange/',   ...
     '|                      75265-euler-free-body-motion',                  ...
     '|',                                                                    ...
     '|           [ 4.2 ]  github.com/phymhan/matlab-axis-label-alignment',  ...
     '|                    www.mathworks.com/matlabcentral/fileexchange/',   ...
     '|                      49542-phymhan-matlab-axis-label-alignment',     ...
     '|',                                                                    ...
     '|           [ 4.3 ]  www.mathworks.com/matlabcentral/fileexchange/',   ...
     '|                      25372-marrow3-m-easy-to-use-3d-arrow',          ...
     '|',                                                                    ...
     '====================================================================', ...
     '==========='                                                           ...
   );
%------------------------------------------------------------------------------- 
   return;
%}------------------------------------------------------------------------------
