function                                                                     ...
generatePlots3D                                                              ...
     (                                                                       ...
       colors,                                                               ...
       angularVelocitiesBodyCoords,                                          ...
       angularMomentumsBodyCoord,                                            ...
       rotationalKineticEnergies,                                            ...
       momentOfInertiaMatrix,                                                ...
       demonstrationTitle                                                    ...
     )
%===============================================================================
%|
%|  FUNCTION:
%|
%|    generatePlots3D
%|
%|-----------------------------------------------------------------------------
%|
%|  PURPOSE:
%|
%|    Project the angular velocity and angular momentum onto their
%|    respective conserved constructs.
%|    Angular velocity is projected onto energy   conservation.
%|    Angular momentum is projected onto momentum conservation.
%|
%|-----------------------------------------------------------------------------
%|
%|  INPUTS:
%|
%|    colors
%|       A data structure containing color information.
%|       UNIT(s):   [nondimensional]
%|
%|    angularVelocitiesBodyCoords
%|      A two dimensional matrix the ith column of which is the
%|      angular velocity in non-inertial body coordinates for
%|      the ith sample time.
%|      UNIT(s):  [radians/second]
%|
%|    angularMomentumsBodyCoord
%|      A two dimensional matrix the ith column of which is the
%|      angular momentum in non-inertial body coordinates
%|      for the ith sample time.
%|      UNIT(s):  [kilograms meter squared / second]
%|
%|    rotationalKineticEnergies
%|      A one dimensional vector the ith element of which is the
%|      rotational kinetic energy of the ith sample time.
%|      UNIT(s):  []
%|
%|    momentOfInertiaMatrix
%|      A three by three matrix of double precision floating point Inertia
%|      Tensor values.
%|      UNIT(s):  [kilograms/meter squared]
%|
%|    demonstrationTitle
%|      A characterstring containing the title of the demonstration.
%|      UNIT(s):  [nondimensional]
%|
%|-----------------------------------------------------------------------------
%|
%|  OUTPUTS:
%|
%|    None
%|
%|-----------------------------------------------------------------------------
%|
%|  USAGE:
%|
%|    generatePlots3D                             ...
%|            (                                   ...
%|              colors,                           ...
%|              angularVelocitiesBodyCoords,      ...
%|              angularMomentumsBodyCoord,        ...
%|              rotationalKineticEnergies,        ...
%|              momentOfInertiaMatrix,            ...
%|              demonstrationTitle                ...
%|            );
%|
%===============================================================================

%===============================================================================
%        1         2         3         4         5         6         7         8
%2345678901234567890123456789012345678901234567890123456789012345678901234567890
%===============================================================================

%{------------------------------------------------------------------------------
   SOLID_LINE  = '-';
   DASHED_LINE = '--';
   DOTTED_LINE = ':';
   DISK_MARKER = 'o';
%===============================================================================
   figure1Units      = 'Normalized';
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   figure1LowerLeftX = 0.0000;
   figure1LowerLeftY = 0.0000;
   figure1Width      = 0.7500;
   figure1Height     = 0.7500;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   figure1Position  = [                                                      ...
                        figure1LowerLeftX;                                   ...
                        figure1LowerLeftY;                                   ...
                        figure1Width;                                        ...
                        figure1Height                                        ...
                      ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     figure1Handle                                                           ...
   ] = figure                                                                ...
         (                                                                   ...
           'Units',         figure1Units,                                    ...
           'Position',      figure1Position                                  ...
         );
%-------------------------------------------------------------------------------
   numberFigure1Children = figure1Handle.Children;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   if( numberFigure1Children > 0 )
    %{--------------------------------------------------------------------------
       clf;
    %}--------------------------------------------------------------------------
   end;
%-------------------------------------------------------------------------------
%  Obtain the Principal Moments of Inertia in ordered fashion.
%-------------------------------------------------------------------------------
   orderedPrincipalMomentsOfInertiaVector = ordeig( momentOfInertiaMatrix );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   J1 = orderedPrincipalMomentsOfInertiaVector( 1 );
   J2 = orderedPrincipalMomentsOfInertiaVector( 2 );
   J3 = orderedPrincipalMomentsOfInertiaVector( 3 );
%-------------------------------------------------------------------------------
%  Energy Ellipsoid
%  Semimajor axes
%-------------------------------------------------------------------------------
   xAxisEnergyEllipsoid =                                                    ...
        sqrt( ( 2.0 * rotationalKineticEnergies( 1 ) ) / J1 );
   yAxisEnergyEllipsoid =                                                    ...
        sqrt( ( 2.0 * rotationalKineticEnergies( 1 ) ) / J2 );
   zAxisEnergyEllipsoid =                                                    ...
        sqrt( ( 2.0 * rotationalKineticEnergies( 1 ) ) / J3 );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   numberLatitudeAndLongitudeGridPoints = 50.0;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     xEnergyEllipsoid,                                                       ...
     yEnergyEllipsoid,                                                       ...
     zEnergyEllipsoid                                                        ...
   ] = ellipsoid                                                             ...
          (                                                                  ...
            0.0,                                                             ...
            0.0,                                                             ...
            0.0,                                                             ...
            xAxisEnergyEllipsoid,                                            ...
            yAxisEnergyEllipsoid,                                            ...
            zAxisEnergyEllipsoid,                                            ...
            numberLatitudeAndLongitudeGridPoints                             ...
          );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     energyEllipsoid                                                         ...
   ] = surf                                                                  ...
        (                                                                    ...
          xEnergyEllipsoid,                                                  ...
          yEnergyEllipsoid,                                                  ...
          zEnergyEllipsoid                                                   ...
        );
   energyEllipsoid.FaceColor = colors.Green;
   energyEllipsoid.EdgeColor = colors.Gray;
   energyEllipsoid.FaceAlpha = 0.4;
   energyEllipsoid.LineStyle = DOTTED_LINE;
   energyEllipsoid.LineWidth = 0.1;
%-------------------------------------------------------------------------------
   hold on;
   grid on;
%-------------------------------------------------------------------------------
%  Plot Origin and Axes
%-------------------------------------------------------------------------------
   scatter3                                                                  ...
      (                                                                      ...
         0.0,                                                                ...
         0.0,                                                                ...
         0.0,                                                                ...
        40.0,                                                                ...
        'Marker',                DISK_MARKER,                                ...
        'MarkerEdgeColor',       colors.Black,                               ...
        'MarkerFaceColor',       colors.Black                                ...
      );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   plot3                                                                     ...
      (                                                                      ...
        [ -xAxisEnergyEllipsoid,  xAxisEnergyEllipsoid ],                    ...
        [  0.0,                   0.0                  ],                    ...
        [  0.0,                   0.0                  ],                    ...
        'LineStyle',              DASHED_LINE,                               ...
        'Color',                  colors.Black,                              ...
        'LineWidth',              2.0                                        ...
      );
   plot3                                                                     ...
      (                                                                      ...
        [  0.0,                   0.0                  ],                    ...
        [ -yAxisEnergyEllipsoid,  yAxisEnergyEllipsoid ],                    ...
        [  0.0,                   0.0                  ],                    ...
        'LineStyle',              DASHED_LINE,                               ...
        'Color',                  colors.Black,                              ...
        'LineWidth',              2.0                                        ...
      );
   plot3                                                                     ...
      (                                                                      ...
        [  0.0,                   0.0                  ],                    ...
        [  0.0,                   0.0                  ],                    ...
        [ -zAxisEnergyEllipsoid,  zAxisEnergyEllipsoid ],                    ...
        'LineStyle',              DASHED_LINE,                               ...
        'Color',                  colors.Black,                              ...
        'LineWidth',              2.0                                        ...
      );
%-------------------------------------------------------------------------------
%  Simply plot angular velocity values, and they should lie on the ellipsoid
%  when energy is conserved
%-------------------------------------------------------------------------------
   plot3                                                                     ...
      (                                                                      ...
        angularVelocitiesBodyCoords( 1, : ),                                 ...
        angularVelocitiesBodyCoords( 2, : ),                                 ...
        angularVelocitiesBodyCoords( 3, : ),                                 ...
        'Color',            'Red',                                           ...
        'LineStyle',        SOLID_LINE,                                      ...
        'LineWidth',        2.5                                              ...
      );
%-------------------------------------------------------------------------------
   [                                                                         ...
     currentAxes1Handle                                                      ...
   ] = gca( figure1Handle );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
%@ set                                                                       ...
%@  (                                                                        ...
%@    currentAxes1Handle,                                                    ...
%@    'Projection',                'Perspective'                             ...
%@  );
   set                                                                       ...
    (                                                                        ...
      currentAxes1Handle,                                                    ...
      'Projection',                'Orthographic'                            ...
    );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      currentAxes1Handle,                                                    ...
      'FontName',                  'Helvetica',                              ...
      'FontSize',                  10,                                       ...
      'FontWeight',                'Bold'                                    ...
    );
%-------------------------------------------------------------------------------
   [                                                                         ...
     titleString1                                                            ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s\n%s\n',                                                    ...
          demonstrationTitle,                                                ...
          'PATH OF ANGULAR VELOCITY VECTOR',                                 ...
          'ON POINSOT''S ELLIPSOID'                                          ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     title1Handle                                                            ...
   ] = title                                                                 ...
        (                                                                    ...
          titleString1,                                                      ...
          'FontName',            'Helvetica',                                ...
          'FontSize',            16,                                         ...
          'FontWeight',          'Bold'                                      ...
        );
%-------------------------------------------------------------------------------
   [                                                                         ...
     xLabelString1                                                           ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'X',                                                               ...
          '[meters / second]'                                                ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     xLabel1Handle                                                           ...
   ] = xlabel                                                                ...
         (                                                                   ...
           xLabelString1,                                                    ...
           'FontName',              'Helvetica',                             ...
           'FontSize',              12,                                      ...
           'FontWeight',            'Bold',                                  ...
           'HorizontalAlignment',   'Center'                                 ...
         );
%-------------------------------------------------------------------------------
   [                                                                         ...
     yLabelString1                                                           ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'Y',                                                               ...
          '[meters / second]'                                                ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     yLabel1Handle                                                           ...
   ] = ylabel                                                                ...
         (                                                                   ...
           yLabelString1,                                                    ...
           'FontName',              'Helvetica',                             ...
           'FontSize',              12,                                      ...
           'FontWeight',            'Bold',                                  ...
           'HorizontalAlignment',   'Center'                                 ...
         );
%-------------------------------------------------------------------------------
   [                                                                         ...
     zLabelString1                                                           ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'Z',                                                               ...
          '[meters / second]'                                                ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     zLabel1Handle                                                           ...
   ] = zlabel                                                                ...
         (                                                                   ...
           zLabelString1,                                                    ...
           'FontName',          'Helvetica',                                 ...
           'FontSize',          12,                                          ...
           'FontWeight',        'Bold'                                       ...
         );
%-------------------------------------------------------------------------------
   R = max(                                                                  ...
            [                                                                ...
              xAxisEnergyEllipsoid,                                          ...
              yAxisEnergyEllipsoid,                                          ...
              zAxisEnergyEllipsoid                                           ...
            ]                                                                ...
          );
   axis                                                                      ...
     (                                                                       ...
       [                                                                     ...
         -R,   R,                                                            ...
         -R,   R,                                                            ...
         -R,   R                                                             ...
       ]                                                                     ...
     );
%-------------------------------------------------------------------------------
%  Enable 3D axes label alignment for interactive rotation.
%-------------------------------------------------------------------------------
   handleRotate3D2 = rotate3d;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      handleRotate3D2,                                                       ...
      'ActionPreCallBack',        @alignAxesLabels                           ...
    );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      handleRotate3D2,                                                       ...
      'ActionPostCallBack',                                                  ...
                'set( gcf, ''windowButtonMotionFcn'', '''' )'                ...
    );
%-------------------------------------------------------------------------------
%  Generate a default invocation of the axes label alignment
%  function to get the 3D axes labels aligned.
%-------------------------------------------------------------------------------
   alignAxesLabels( currentAxes1Handle, [ ] );
%===============================================================================
   figure2Units      = 'Normalized';
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   figure2LowerLeftX = 0.1000;
   figure2LowerLeftY = 0.0000;
   figure2Width      = 0.7500;
   figure2Height     = 0.7500;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   figure2Position  = [                                                      ...
                        figure2LowerLeftX;                                   ...
                        figure2LowerLeftY;                                   ...
                        figure2Width;                                        ...
                        figure2Height                                        ...
                      ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     figure2Handle                                                           ...
   ] = figure                                                                ...
         (                                                                   ...
           'Units',         figure2Units,                                    ...
           'Position',      figure2Position                                  ...
         );
%-------------------------------------------------------------------------------
   numberFigure2Children = figure2Handle.Children;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   if( numberFigure2Children > 0 )
    %{--------------------------------------------------------------------------
       clf;
    %}--------------------------------------------------------------------------
   end;
%-------------------------------------------------------------------------------
%  Create Momentum Sphere
%-------------------------------------------------------------------------------
   numberLatitudeAndLongitudeGridPoints = 100.0;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     xMomentumSphere,                                                        ...
     yMomentumSphere,                                                        ...
     zMomentumSphere                                                         ...
   ] = sphere                                                                ...
         (                                                                   ...
           numberLatitudeAndLongitudeGridPoints                              ...
         );
%-------------------------------------------------------------------------------
   angularMomentum1Norm = vecnorm( angularMomentumsBodyCoord( :, 1 ) );
%-------------------------------------------------------------------------------
%  Normalize sphere default points to momentum size
%-------------------------------------------------------------------------------
   xScaledMomentumSphere = angularMomentum1Norm * xMomentumSphere;
   yScaledMomentumSphere = angularMomentum1Norm * yMomentumSphere;
   zScaledMomentumSphere = angularMomentum1Norm * zMomentumSphere;
% - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     angularMomentumSphere                                                   ...
   ] = surf                                                                  ...
        (                                                                    ...
          xScaledMomentumSphere,                                             ...
          yScaledMomentumSphere,                                             ...
          zScaledMomentumSphere                                              ...
        );
   angularMomentumSphere.FaceAlpha = 0.4;
   angularMomentumSphere.FaceColor = colors.Green;
   angularMomentumSphere.EdgeColor = colors.Gray;
   angularMomentumSphere.LineStyle = DOTTED_LINE;
   angularMomentumSphere.LineWidth = 0.1;
%-------------------------------------------------------------------------------
   hold on;
   grid on;
%-------------------------------------------------------------------------------
%  Plot Origin
%-------------------------------------------------------------------------------
   scatter3                                                                  ...
      (                                                                      ...
        0.0,                                                                 ...
        0.0,                                                                 ...
        0.0,                                                                 ...
        40,                                                                  ...
        'Marker',                DISK_MARKER,                                ...
        'MarkerEdgeColor',       colors.Black,                               ...
        'MarkerFaceColor',       colors.Black                                ...
      );
%-------------------------------------------------------------------------------
%  Plot X Body Axis
%-------------------------------------------------------------------------------
   plot3                                                                     ...
     (                                                                       ...
       1.3 *                                                                 ...
       [                                                                     ...
         -angularMomentum1Norm,                                              ...
         angularMomentum1Norm                                                ...
       ],                                                                    ...
       [                                                                     ...
         0.0,                                                                ...
         0.0                                                                 ...
       ],                                                                    ...
       [                                                                     ...
         0.0,                                                                ...
         0.0                                                                 ...
       ],                                                                    ...
       'Color',                colors.Black,                                 ...
       'LineStyle',            DASHED_LINE,                                  ...
       'LineWidth',            2.0                                           ...
     );
%-------------------------------------------------------------------------------
%  Plot Y Body Axis
%-------------------------------------------------------------------------------
   plot3                                                                     ...
     (                                                                       ...
       [                                                                     ...
         0.0,                                                                ...
         0.0                                                                 ...
       ],                                                                    ...
       1.3 *                                                                 ...
       [                                                                     ...
         -angularMomentum1Norm,                                              ...
         angularMomentum1Norm                                                ...
       ],                                                                    ...
       [                                                                     ...
         0.0,                                                                ...
         0.0                                                                 ...
       ],                                                                    ...
       'Color',                colors.Black,                                 ...
       'LineStyle',            DASHED_LINE,                                  ...
       'LineWidth',            2.0                                           ...
     );
%-------------------------------------------------------------------------------
%  Plot Z Body Axis
%-------------------------------------------------------------------------------
   plot3                                                                     ...
     (                                                                       ...
       [                                                                     ...
         0.0,                                                                ...
         0.0                                                                 ...
       ],                                                                    ...
       [                                                                     ...
         0.0,                                                                ...
         0.0                                                                 ...
       ],                                                                    ...
       1.3 *                                                                 ...
       [                                                                     ...
         -angularMomentum1Norm,                                              ...
         angularMomentum1Norm                                                ...
       ],                                                                    ...
       'Color',                colors.Black,                                 ...
       'LineStyle',            DASHED_LINE,                                  ...
       'LineWidth',            2.0                                           ...
     );
%-------------------------------------------------------------------------------
%  Projection of angular momentum onto sphere
%-------------------------------------------------------------------------------
   plot3                                                                     ...
     (                                                                       ...
       angularMomentumsBodyCoord( 1, : ),                                    ...
       angularMomentumsBodyCoord( 2, : ),                                    ...
       angularMomentumsBodyCoord( 3, : ),                                    ...
       'Color',                colors.Red,                                   ...
       'LineStyle',            SOLID_LINE,                                   ...
       'LineWidth',            3.0                                           ...
     );
%-------------------------------------------------------------------------------
   [                                                                         ...
     currentAxes2Handle                                                      ...
   ] = gca( figure2Handle );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
%@ set                                                                       ...
%@  (                                                                        ...
%@    currentAxes2Handle,                                                    ...
%@    'Projection',                'Perspective'                             ...
%@  );
   set                                                                       ...
    (                                                                        ...
      currentAxes2Handle,                                                    ...
      'Projection',                'Orthographic'                            ...
    );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      currentAxes2Handle,                                                    ...
      'FontName',                  'Helvetica',                              ...
      'FontSize',                  10,                                       ...
      'FontWeight',                'Bold'                                    ...
    );
%-------------------------------------------------------------------------------
   [                                                                         ...
     titleString2                                                            ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s\n%s\n',                                                    ...
          demonstrationTitle,                                                ...
          'PATH OF ANGULAR MOMENTUM VECTOR',                                 ...
          'ON INERTIAL SPHERE'                                               ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     title2Handle                                                            ...
   ] = title                                                                 ...
        (                                                                    ...
           titleString2,                                                     ...
           'FontName',           'Helvetica',                                ...
           'FontSize',           16,                                         ...
           'FontWeight',         'Bold'                                      ...
        );
%-------------------------------------------------------------------------------
   [                                                                         ...
     xLabelString2                                                           ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'X',                                                               ...
          '[Newton meter seconds]'                                           ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     xLabel2Handle                                                           ...
   ] = xlabel                                                                ...
        (                                                                    ...
          xLabelString2,                                                     ...
          'FontName',              'Helvetica',                              ...
          'FontSize',              12,                                       ...
          'FontWeight',            'Bold',                                   ...
          'HorizontalAlignment',   'Center'                                  ...
        );
%-------------------------------------------------------------------------------
   [                                                                         ...
     yLabelString2                                                           ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'Y',                                                               ...
          '[Newton meter seconds]'                                           ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     yLabel2Handle                                                           ...
   ] = ylabel                                                                ...
        (                                                                    ...
          yLabelString2,                                                     ...
          'FontName',              'Helvetica',                              ...
          'FontSize',              12,                                       ...
          'FontWeight',            'Bold',                                   ...
          'HorizontalAlignment',   'Center'                                  ...
        );
%-------------------------------------------------------------------------------
   [                                                                         ...
     zLabelString2                                                           ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'Z',                                                               ...
          '[Newton meter seconds]'                                           ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     zLabel2Handle                                                           ...
   ] = zlabel                                                                ...
        (                                                                    ...
          zLabelString2,                                                     ...
          'FontName',           'Helvetica',                                 ...
          'FontSize',           12,                                          ...
          'FontWeight',         'Bold'                                       ...
        );
%-------------------------------------------------------------------------------
   axis equal;
%-------------------------------------------------------------------------------
%  Enable 3D axes label alignment for interactive rotation.
%-------------------------------------------------------------------------------
   handleRotate3D = rotate3d;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      handleRotate3D,                                                        ...
      'ActionPreCallBack',        @alignAxesLabels                           ...
    );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      handleRotate3D,                                                        ...
      'ActionPostCallBack',                                                  ...
                'set( gcf, ''windowButtonMotionFcn'', '''' )'                ...
    );
%-------------------------------------------------------------------------------
%  Generate a default invocation of the axes label alignment
%  function to get the 3D axes labels aligned.
%-------------------------------------------------------------------------------
   alignAxesLabels( currentAxes2Handle, [ ] );
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------
