function                                                                     ...
performNonRealTimeAnimationPlayBack3D                                        ...
       (                                                                     ...
         colors,                                                             ...
         timeSampleValues,                                                   ...
         referencePosition,                                                  ...
         rotationVectorsBodyCoords,                                          ...
         angularVelocitiesInertialCoords,                                    ...
         angularMomentumsInertialCoords,                                     ...
         momentsOfInertiaMatrix,                                             ...
         skipRateFactor,                                                     ...
         demonstrationTitle                                                  ...
       )
%===============================================================================
%|
%|  FUNCTION:
%|
%|    performNonRealTimeAnimationPlayBack3D
%|
%|-----------------------------------------------------------------------------
%|
%|  PURPOSE:
%|
%|    Perform non real time animation play back of a rotating 3D rectangular
%|    solid rigid object.
%|
%|-----------------------------------------------------------------------------
%|
%|  INPUT(s):
%|
%|     colors
%|       A data structure containing color information.
%|       UNIT(s):   [nondimensional]
%|
%|     timeSampleValues
%|       A vector of double precision floating point values the ith element
%|       of which is the ith time value.
%|       UNIT(s):   [seconds]
%|
%|     referencePosition
%|       A one dimensional vector of length three containing the
%|       reference position of the object.
%|       UNIT(s):   [meters]
%|
%|     rotationVectorsBodyCoords
%|       A two dimensional array with three rows.
%|       The jth column contains the rotation vector in non-inertial body
%|       coordinates for the jth time.
%|       UNIT(s):   [radians]
%|
%|     angularVelocitiesInertialCoords
%|       A two dimensional array with three rows.
%|       The jth column is the angular velocity in nertial
%|       coordinates for the ith sample time.
%|       UNIT(s):   [radians/second]
%|
%|    angularMomentumsInertialCoord
%|      A two dimensional matrix the ith column of which is the
%|      angular momentum in inertial coordinates
%|      for the ith sample time.
%|      UNIT(s):  [kilograms meter squared / second]
%|
%|     momentsOfInertiaMatrix
%|       A three by three matrix containing the moment of inertia.
%|       UNIT(s):   [kilograms meters squared]
%|
%|     skipRateFactor
%|       An integer which is the number of time samples to skip before
%|       displaying the next 3D animation frame.
%|       UNIT(s):   [nondimensional]
%|
%|     demonstrationTitle
%|       A character string containing the title of the demostration.
%|       UNIT(s):   [nondimensional]
%|
%|-----------------------------------------------------------------------------
%|
%|  OUTPUT(s):
%|
%|     None
%|
%|-----------------------------------------------------------------------------
%|
%|  RETURN VALUE(s):
%|
%|     None
%|
%|-----------------------------------------------------------------------------
%|
%|  NOTE(s):
%|
%|     [ 1 ]  The principle moments of inertia values are used to make
%|            a proportionally sized rectangular solid rigid block.
%|
%===============================================================================

%===============================================================================
%        1         2         3         4         5         6         7         8
%2345678901234567890123456789012345678901234567890123456789012345678901234567890
%===============================================================================

%{------------------------------------------------------------------------------
%  Obtain the "size" of the rectangular block object from the principle
%  components of the moments of inertia matrix.
%-------------------------------------------------------------------------------
   principleMomentsOfInertiaVector = diag( momentsOfInertiaMatrix );
   inertiaSizeVector               = principleMomentsOfInertiaVector /       ...
                                     vecnorm                                 ...
                                      ( principleMomentsOfInertiaVector );
%-------------------------------------------------------------------------------
   objectDimensionX        = inertiaSizeVector( 1 );
   objectDimensionY        = inertiaSizeVector( 2 );
   objectDimensionZ        = inertiaSizeVector( 3 );
   objectMaximumDimensionX = max( abs( objectDimensionX ) );
   objectMaximumDimensionY = max( abs( objectDimensionY ) );
   objectMaximumDimensionZ = max( abs( objectDimensionZ ) );
   objectMaximumDimension  = max(                                            ...
                                  [                                          ...
                                    objectMaximumDimensionX,                 ...
                                    objectMaximumDimensionY,                 ...
                                    objectMaximumDimensionZ                  ...
                                  ]                                          ...
                                );
%-------------------------------------------------------------------------------
   figureUnits      = 'Normalized';
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   figureLowerLeftX = 0.0250;
   figureLowerLeftY = 0.0000;
   figureWidth      = 0.9000;
   figureHeight     = 0.9000;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   figure4Position  = [                                                      ...
                        figureLowerLeftX;                                    ...
                        figureLowerLeftY;                                    ...
                        figureWidth;                                         ...
                        figureHeight                                         ...
                      ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     figureHandle                                                            ...
   ] = figure                                                                ...
         (                                                                   ...
           'Units',         figureUnits,                                     ...
           'Position',      figure4Position                                  ...
         );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   clf( figureHandle );
   currentAxesHandle                 = gca;
%-------------------------------------------------------------------------------
   axesLimits                        = [                                     ...
                                         -objectMaximumDimension;            ...
                                          objectMaximumDimension             ...
                                       ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   currentAxesHandle.XLim            = axesLimits;
   currentAxesHandle.YLim            = axesLimits;
   currentAxesHandle.ZLim            = axesLimits;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
%  currentAxesHandle.Projection      = "perspective";
   currentAxesHandle.Projection      = "orthographic";
   currentAxesHandle.DataAspectRatio = [ 1.0, 1.0, 1.0 ];
%-------------------------------------------------------------------------------
   grid( currentAxesHandle, 'on' );
   hold( currentAxesHandle, 'on' );
%-------------------------------------------------------------------------------
   [                                                                         ...
     transformationHandle                                                    ...
   ] = hgtransform                                                           ...
         (                                                                   ...
           'Parent',       currentAxesHandle                                 ...
         );
%-------------------------------------------------------------------------------
   [                                                                         ...
     objectHandleVector                                                      ...
   ] = createObject                                                          ...
             (                                                               ...
               colors,                                                       ...
               objectMaximumDimensionX,                                      ...
               objectMaximumDimensionY,                                      ...
               objectMaximumDimensionZ,                                      ...
               referencePosition,                                            ...
               currentAxesHandle                                             ...
             );
%-------------------------------------------------------------------------------
   view( 120, 10 );
   set                                                                       ...
    (                                                                        ...
       objectHandleVector,                                                   ...
       'Parent',      transformationHandle                                   ...
    );
%-------------------------------------------------------------------------------
   set                                                                       ...
    (                                                                        ...
      currentAxesHandle,                                                     ...
      'FontName',                  'Helvetica',                              ...
      'FontSize',                  12,                                       ...
      'FontWeight',                'Bold'                                    ...
    );
%-------------------------------------------------------------------------------
   initialTime  = timeSampleValues(   1 );
   finalTime    = timeSampleValues( end );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     titleString                                                             ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s\n%s% 8.2f / % 8.2f%s\n',                                   ...
          demonstrationTitle,                                                ...
          '3D ANIMATION PLAY BACK',                                          ...
          'Simulation Time: ',                                               ...
          initialTime,                                                       ...
          finalTime,                                                         ...
          ' [seconds]'                                                       ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     titleHandle                                                             ...
   ]  = title                                                                ...
         (                                                                   ...
           titleString,                                                      ...
          'FontName',            'Helvetica',                                ...
          'FontSize',            24,                                         ...
          'FontWeight',          'Bold'                                      ...
         );
%-------------------------------------------------------------------------------
   [                                                                         ...
     xLabelString                                                            ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'X_{Inertial}',                                                    ...
          '[meters]'                                                         ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     xLabelHandle                                                            ...
   ] = xlabel                                                                ...
        (                                                                    ...
          xLabelString,                                                      ...
          'FontName',            'Helvetica',                                ...
          'FontSize',            16,                                         ...
          'FontWeight',          'Bold'                                      ...
        );
%-------------------------------------------------------------------------------
   [                                                                         ...
     yLabelString                                                            ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'Y_{Inertial}',                                                    ...
          '[meters]'                                                         ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     yLabelHandle                                                            ...
   ] = ylabel                                                                ...
        (                                                                    ...
          yLabelString,                                                      ...
          'FontName',            'Helvetica',                                ...
          'FontSize',            16,                                         ...
          'FontWeight',          'Bold'                                      ...
        );
%-------------------------------------------------------------------------------
   [                                                                         ...
     zLabelString                                                            ...
   ] = sprintf                                                               ...
        (                                                                    ...
          '%s\n%s',                                                          ...
          'Z_{Inertial}',                                                    ...
          '[meters]'                                                         ...
        );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     zLabelHandle                                                            ...
   ] = zlabel                                                                ...
        (                                                                    ...
          zLabelString,                                                      ...
          'FontName',            'Helvetica',                                ...
          'FontSize',            16,                                         ...
          'FontWeight',          'Bold'                                      ...
        );
%-------------------------------------------------------------------------------
%  Enable 3D axes label alignment for interactive rotation.
%-------------------------------------------------------------------------------
   handleRotate3D = rotate3d;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      handleRotate3D,                                                        ...
      'ActionPreCallBack',        @alignAxesLabels                           ...
    );
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   set                                                                       ...
    (                                                                        ...
      handleRotate3D,                                                        ...
      'ActionPostCallBack',                                                  ...
                'set( gcf, ''windowButtonMotionFcn'', '''' )'                ...
    );
%-------------------------------------------------------------------------------
%  Generate a default invocation of the axes label alignment
%  function to get the 3D axes labels aligned.
%-------------------------------------------------------------------------------
   alignAxesLabels( currentAxesHandle, [ ] );
%-------------------------------------------------------------------------------
   if( skipRateFactor > 0 )
    %{--------------------------------------------------------------------------
    %  User has specified that a non-trivial number of time samples are to
    %  be skipped when displaying results.
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %  Loop over time samples and skip the specified number of time samples.
    %---------------------------------------------------------------------------
       numberTimeSamples = length( timeSampleValues );
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       angularMomentumVectorPatchGraphicsHandle = [ ];
       angularMomentumVectorLabelTextBoxHandle  = [ ];
       angularVelocityVectorPatchGraphicsHandle = [ ];
       angularVelocityVectorLabelTextBoxHandle  = [ ];
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       for( timeSampleIndex = 1 : skipRateFactor : numberTimeSamples )
         %{---------------------------------------------------------------------
            pause( 0.001 );
         %----------------------------------------------------------------------
            currentRotationVectorBodyCoords       =                          ...
                                           rotationVectorsBodyCoords         ...
                                                   ( :, timeSampleIndex );
            currentAngularVelocityVectorInertialCoord =                      ...
                                           angularVelocitiesInertialCoords   ...
                                                   ( :, timeSampleIndex );
            currentAngularMomentumVectorInertialCoord =                      ...
                                           angularMomentumsInertialCoords    ...
                                                   ( :, timeSampleIndex );
         %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
            [                                                                ...
              updatedTransformationHandle                                    ...
              updatedAngularMomentumVectorPatchGraphicsHandle,               ...
              updatedAngularMomentumVectorLabelTextBoxHandle,                ...
              updatedAngularVelocityVectorPatchGraphicsHandle,               ...
              updatedAngularVelocityVectorLabelTextBoxHandle                 ...
            ] = moveObject                                                   ...
                    (                                                        ...
                      colors,                                                ...
                      transformationHandle,                                  ...
                      angularMomentumVectorPatchGraphicsHandle,              ...
                      angularMomentumVectorLabelTextBoxHandle,               ...
                      angularVelocityVectorPatchGraphicsHandle,              ...
                      angularVelocityVectorLabelTextBoxHandle,               ...
                      currentRotationVectorBodyCoords,                       ...
                      referencePosition,                                     ...
                      currentAngularVelocityVectorInertialCoord,             ...
                      currentAngularMomentumVectorInertialCoord              ...
                    );
         %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
            transformationHandle                     =                       ...
                           updatedTransformationHandle;
            angularMomentumVectorPatchGraphicsHandle =                       ...
                           updatedAngularMomentumVectorPatchGraphicsHandle;
            angularMomentumVectorLabelTextBoxHandle  =                       ...
                           updatedAngularMomentumVectorLabelTextBoxHandle;
            angularVelocityVectorPatchGraphicsHandle =                       ...
                           updatedAngularVelocityVectorPatchGraphicsHandle;
            angularVelocityVectorLabelTextBoxHandle  =                       ...
                           updatedAngularVelocityVectorLabelTextBoxHandle;
         %----------------------------------------------------------------------
            currentTime = timeSampleValues( timeSampleIndex );
         %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
            [                                                                ...
              titleHandle.String                                             ...
            ] = sprintf                                                      ...
                 (                                                           ...
                   '%s\n%s\n%s% 7d / % 7d\n%s% 8.2f / % 8.2f%s\n',           ...
                   demonstrationTitle,                                       ...
                   '3D ANIMATION PLAY BACK',                                 ...
                   'Frame Index: ',                                          ...
                   timeSampleIndex,                                          ...
                   numberTimeSamples,                                        ...
                   'Simulation Time: ',                                      ...
                   currentTime,                                              ...
                   finalTime,                                                ...
                   ' [seconds]'                                              ...
                 );
         %}---------------------------------------------------------------------
       end;
    %}--------------------------------------------------------------------------
   else
    %{--------------------------------------------------------------------------
    %  User has specified that no time samples are to be skipped when
    %  displaying results.
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %  Loop over all time samples.
    %---------------------------------------------------------------------------
       angularMomentumVectorPatchGraphicsHandle = [ ];
       angularMomentumVectorLabelTextBoxHandle  = [ ];
       angularVelocityVectorPatchGraphicsHandle = [ ];
       angularVelocityVectorLabelTextBoxHandle  = [ ];
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       for( timeSampleIndex = 1 : numberTimeSamples )
         %{---------------------------------------------------------------------
            pause( 0.001 );
         %----------------------------------------------------------------------
            currentRotationVectorBodyCoords       =                          ...
                                        rotationVectorsBodyCoords            ...
                                                   ( :, timeSampleIndex );
            currentAngularVelocityVectorInertialCoord =                      ...
                                        angularVelocitiesInertialCoords      ...
                                                   ( :, timeSampleIndex );
            currentAngularMomentumVectorInertialCoord =                      ...
                                        angularMomentumsInertialCoords       ...
                                                   ( :, timeSampleIndex );
         %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
            [                                                                ...
              updatedTransformationHandle,                                   ...
              updatedAngularMomentumVectorPatchGraphicsHandle,               ...
              updatedAngularMomentumVectorLabelTextBoxHandle,                ...
              updatedAngularVelocityVectorPatchGraphicsHandle,               ...
              updatedAngularVelocityVectorLabelTextBoxHandle                 ...
            ] = moveObject                                                   ...
                    (                                                        ...
                      colors,                                                ...
                      transformationHandle,                                  ...
                      angularMomentumVectorPatchGraphicsHandle,              ...
                      angularMomentumVectorLabelTextBoxHandle,               ...
                      angularVelocityVectorPatchGraphicsHandle,              ...
                      angularVelocityVectorLabelTextBoxHandle,               ...
                      currentRotationVectorBodyCoords,                       ...
                      referencePosition,                                     ...
                      currentAngularVelocityVectorInertialCoord,             ...
                      currentAngularMomentumVectorInertialCoord              ...
                    );
         %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
            transformationHandle                     =                       ...
                           updatedTransformationHandle;
            angularMomentumVectorPatchGraphicsHandle =                       ...
                           updatedAngularMomentumVectorPatchGraphicsHandle;
            angularMomentumVectorLabelTextBoxHandle  =                       ...
                           updatedAngularMomentumVectorLabelTextBoxHandle;
            angularVelocityVectorPatchGraphicsHandle =                       ...
                           updatedAngularVelocityVectorPatchGraphicsHandle;
            angularVelocityVectorLabelTextBoxHandle  =                       ...
                           updatedAngularVelocityVectorLabelTextBoxHandle;
         %----------------------------------------------------------------------
            currentTime = timeSampleValues( timeSampleIndex );
         %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
            [                                                                ...
              titleHandle.String                                             ...
            ] = sprintf                                                      ...
                 (                                                           ...
                   '%s\n%s\n%s% 7d / % 7d\n%s% 8.2f / % 8.2f%s\n',           ...
                   demonstrationTitle,                                       ...
                   '3D ANIMATION PLAY BACK',                                 ...
                   'Frame Index: ',                                          ...
                   timeSampleIndex,                                          ...
                   numberTimeSamples,                                        ...
                   'Simulation Time: ',                                      ...
                   currentTime,                                              ...
                   finalTime,                                                ...
                   ' [seconds]'                                              ...
                 );
         %}---------------------------------------------------------------------
       end;
    %}--------------------------------------------------------------------------
   end;
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
function                                                                     ...
[                                                                            ...
  rectangularSolidObjectHandles                                              ...
] =                                                                          ...
createObject                                                                 ...
      (                                                                      ...
        colors,                                                              ...
        objectMaxDimX,                                                       ...
        objectMaxDimY,                                                       ...
        objectMaxDimZ,                                                       ...
        referencePosition,                                                   ...
        currentAxesHandle                                                    ...
      )
%{------------------------------------------------------------------------------
   DASHED_LINE   = '--';
   DOTTED_LINE   = ':-';
   SOLID_LINE    = '-';
%-------------------------------------------------------------------------------
%
%  NOTE(s):
%
%    [ 1 ] Rotation vector definition:
%          A rotation vector is a one dimensional row or column vector of
%          length three.
%            [ 1.1 ] The norm of the rotation vector is the rotation angle.
%            [ 1.2 ] The normalized rotation vector is a 3D unit vector
%                    which serves as the rotation axis.
%
%-------------------------------------------------------------------------------
   objectMaximumDimension = max(                                             ...
                                 [                                           ...
                                   objectMaxDimX;                            ...
                                   objectMaxDimY;                            ...
                                   objectMaxDimZ                             ...
                                 ]                                           ...
                               );
%-------------------------------------------------------------------------------
   objectFace1Color = colors.IndianRed1;
   objectFace2Color = colors.Green;
   objectFace3Color = colors.HotPink1;
   objectFace4Color = colors.Gold1;
   objectFace5Color = colors.RoyalBlue1;
   objectFace6Color = colors.Orange1;
%-------------------------------------------------------------------------------
%  Create the six faces of a 3D rectangular object.
%-------------------------------------------------------------------------------
   objectFaceVerticesX =                                                     ...
    [                                                                        ...
      0.0,            0.0,            0.0,            0.0;                   ...
      objectMaxDimX,  objectMaxDimX,  objectMaxDimX,  objectMaxDimX;         ...
      0.0,            objectMaxDimX,  objectMaxDimX,  0.0;                   ...
      0.0,            objectMaxDimX,  objectMaxDimX,  0.0;                   ...
      0.0,            objectMaxDimX,  objectMaxDimX,  0.0;                   ...
      0.0,            objectMaxDimX,  objectMaxDimX,  0.0                    ...
    ];
   objectFaceVerticesY =                                                     ...
    [                                                                        ...
      0.0,            0.0,            objectMaxDimY,  objectMaxDimY;         ...
      0.0,            0.0,            objectMaxDimY,  objectMaxDimY;         ...
      0.0,            0.0,            0.0,            0.0;                   ...
      objectMaxDimY,  objectMaxDimY,  objectMaxDimY,  objectMaxDimY;         ...
      0.0,            0.0,            objectMaxDimY,  objectMaxDimY;         ...
      0.0,            0.0,            objectMaxDimY,  objectMaxDimY          ...
    ];
   objectFaceVerticesZ =                                                     ...
    [                                                                        ...
      0.0,            objectMaxDimZ,  objectMaxDimZ,  0.0;                   ...
      0.0,            objectMaxDimZ,  objectMaxDimZ,  0.0;                   ...
      0.0,            0.0,            objectMaxDimZ,  objectMaxDimZ;         ...
      0.0,            0.0,            objectMaxDimZ,  objectMaxDimZ;         ...
      0.0,            0.0,            0.0,            0.0;                   ...
      objectMaxDimZ,  objectMaxDimZ,  objectMaxDimZ,  objectMaxDimZ          ...
    ];
%-------------------------------------------------------------------------------
%  Center the 3D rectangular object at the origin.
%-------------------------------------------------------------------------------
   objectFaceVerticesX = objectFaceVerticesX - ( objectMaxDimX / 2.0 );
   objectFaceVerticesY = objectFaceVerticesY - ( objectMaxDimY / 2.0 );
   objectFaceVerticesZ = objectFaceVerticesZ - ( objectMaxDimZ / 2.0 );
%-------------------------------------------------------------------------------
%  Center the 3D rectangular object at the specified reference position.
%-------------------------------------------------------------------------------
   objectFaceVerticesX = objectFaceVerticesX + referencePosition( 1 );
   objectFaceVerticesY = objectFaceVerticesY + referencePosition( 2 );
   objectFaceVerticesZ = objectFaceVerticesZ + referencePosition( 3 );
%-------------------------------------------------------------------------------
%  Create the six filled face areas for the 3D rectangular object.
%-------------------------------------------------------------------------------
   [                                                                         ...
     rectangularSolidFace1Handle                                             ...
   ] = fill3                                                                 ...
        (                                                                    ...
          currentAxesHandle,                                                 ...
          objectFaceVerticesX( 1, : ),                                       ...
          objectFaceVerticesY( 1, : ),                                       ...
          objectFaceVerticesZ( 1, : )',                                      ...
          objectFace1Color',                                                 ...
          'FaceAlpha',                   0.85                                ...
        );
   [                                                                         ...
     rectangularSolidFace2Handle                                             ...
   ] = fill3                                                                 ...
        (                                                                    ...
          currentAxesHandle,                                                 ...
          objectFaceVerticesX( 2, : ),                                       ...
          objectFaceVerticesY( 2, : ),                                       ...
          objectFaceVerticesZ( 2, : ),                                       ...
          objectFace2Color',                                                 ...
          'FaceAlpha',                   0.85                                ...
        );
   [                                                                         ...
     rectangularSolidFace3Handle                                             ...
   ] = fill3                                                                 ...
        (                                                                    ...
          currentAxesHandle,                                                 ...
          objectFaceVerticesX( 3, : ),                                       ...
          objectFaceVerticesY( 3, : ),                                       ...
          objectFaceVerticesZ( 3, : ),                                       ...
          objectFace3Color',                                                 ...
          'FaceAlpha',                   0.85                                ...
        );
   [                                                                         ...
     rectangularSolidFace4Handle                                             ...
   ] = fill3                                                                 ...
        (                                                                    ...
          currentAxesHandle,                                                 ...
          objectFaceVerticesX( 4, : ),                                       ...
          objectFaceVerticesY( 4, : ),                                       ...
          objectFaceVerticesZ( 4, : ),                                       ...
          objectFace4Color',                                                 ...
          'FaceAlpha',                   0.85                                ...
        );
   [                                                                         ...
     rectangularSolidFace5Handle                                             ...
   ] = fill3                                                                 ...
        (                                                                    ...
          currentAxesHandle,                                                 ...
          objectFaceVerticesX( 5, : ),                                       ...
          objectFaceVerticesY( 5, : ),                                       ...
          objectFaceVerticesZ( 5, : ),                                       ...
          objectFace5Color',                                                 ...
          'FaceAlpha',                   0.85                                ...
        );
   [                                                                         ...
     rectangularSolidFace6Handle                                             ...
   ] = fill3                                                                 ...
        (                                                                    ...
          currentAxesHandle,                                                 ...
          objectFaceVerticesX( 6, : ),                                       ...
          objectFaceVerticesY( 6, : ),                                       ...
          objectFaceVerticesZ( 6, : ),                                       ...
          objectFace6Color',                                                 ...
          'FaceAlpha',                   0.85                                ...
        );
%-------------------------------------------------------------------------------
%  Create the initial X body axis entity.
%-------------------------------------------------------------------------------
   specifiedFont              = 'Helvetica';
   specifiedFontSize          = 16;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   xAxisVectorBodyCoordinates = [                                            ...
                                  objectMaximumDimension;                    ...
                                  0.00;                                      ...
                                  0.00                                       ...
                                ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    arrowColor                =  colors.Black;
    labelColor                =  colors.Black;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     xBodyAxisVectorPatchGraphicsHandle,                                     ...
     xAxisVectorLabelTextBoxHandle                                           ...
   ] = createXBodyAxisVector                                                 ...
             (                                                               ...
               arrowColor,                                                   ...
               labelColor,                                                   ...
               referencePosition,                                            ...
               xAxisVectorBodyCoordinates,                                   ...
               specifiedFont,                                                ...
               specifiedFontSize                                             ...
             );
%-------------------------------------------------------------------------------
% Create the initial Y body axis entity.
%-------------------------------------------------------------------------------
   specifiedFont              = 'Helvetica';
   specifiedFontSize          = 16;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   yAxisVectorBodyCoordinates = [                                            ...
                                  0.00;                                      ...
                                  objectMaximumDimension;                    ...
                                  0.00                                       ...
                                ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    arrowColor                =  colors.Black;
    labelColor                =  colors.Black;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     yBodyAxisVectorPatchGraphicsHandle,                                     ...
     yAxisVectorLabelTextBoxHandle                                           ...
   ] = createYBodyAxisVector                                                 ...
             (                                                               ...
               arrowColor,                                                   ...
               labelColor,                                                   ...
               referencePosition,                                            ...
               yAxisVectorBodyCoordinates,                                   ...
               specifiedFont,                                                ...
               specifiedFontSize                                             ...
             );
%-------------------------------------------------------------------------------
% Create the initial Z body axis entity.
%-------------------------------------------------------------------------------
   specifiedFont              = 'Helvetica';
   specifiedFontSize          = 16;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   zAxisVectorBodyCoordinates = [                                            ...
                                  0.00;                                      ...
                                  0.00;                                      ...
                                  objectMaximumDimension                     ...
                                ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    arrowColor                =  colors.Black;
    labelColor                =  colors.Black;
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     zBodyAxisVectorPatchGraphicsHandle,                                     ...
     zAxisVectorLabelTextBoxHandle                                           ...
   ] = createZBodyAxisVector                                                 ...
             (                                                               ...
               arrowColor,                                                   ...
               labelColor,                                                   ...
               referencePosition,                                            ...
               zAxisVectorBodyCoordinates,                                   ...
               specifiedFont,                                                ...
               specifiedFontSize                                             ...
             );
%-------------------------------------------------------------------------------
   rectangularSolidObjectHandles(  1 ) = rectangularSolidFace1Handle;
   rectangularSolidObjectHandles(  2 ) = rectangularSolidFace2Handle;
   rectangularSolidObjectHandles(  3 ) = rectangularSolidFace3Handle;
   rectangularSolidObjectHandles(  4 ) = rectangularSolidFace4Handle;
   rectangularSolidObjectHandles(  5 ) = rectangularSolidFace5Handle;
   rectangularSolidObjectHandles(  6 ) = rectangularSolidFace6Handle;
   rectangularSolidObjectHandles(  7 ) = xBodyAxisVectorPatchGraphicsHandle;
   rectangularSolidObjectHandles(  8 ) = yBodyAxisVectorPatchGraphicsHandle;
   rectangularSolidObjectHandles(  9 ) = zBodyAxisVectorPatchGraphicsHandle;
   rectangularSolidObjectHandles( 10 ) = xAxisVectorLabelTextBoxHandle;
   rectangularSolidObjectHandles( 11 ) = yAxisVectorLabelTextBoxHandle;
   rectangularSolidObjectHandles( 12 ) = zAxisVectorLabelTextBoxHandle;
%-------------------------------------------------------------------------------
   set                                                                       ...
    (                                                                        ...
      currentAxesHandle,                                                     ...
      'FontName',              'Helvetica',                                  ...
      'FontSize',              12,                                           ...
      'FontWeight',            'Bold'                                        ...
    );
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
function                                                                     ...
[                                                                            ...
  updatedTransformationHandle,                                               ...
  updatedAngularMomentumVectorPatchGraphicsHandle,                           ...
  updatedAngularMomentumVectorLabelTextBoxHandle,                            ...
  updatedAngularVelocityVectorPatchGraphicsHandle,                           ...
  updatedAngularVelocityVectorLabelTextBoxHandle                             ...
] =                                                                          ...
moveObject                                                                   ...
    (                                                                        ...
      colors,                                                                ...
      transformationHandle,                                                  ...
      angularMomentumVectorPatchGraphicsHandle,                              ...
      angularMomentumVectorLabelTextBoxHandle,                               ...
      angularVelocityVectorPatchGraphicsHandle,                              ...
      angularVelocityVectorLabelTextBoxHandle,                               ...
      currentRotationVectorBodyCoords,                                       ...
      referencePosition,                                                     ...
      currentAngularVelocityVectorInertialCoord,                             ...
      currentAngularMomentumVectorInertialCoord                              ...
    )
%{------------------------------------------------------------------------------
   if( all( currentRotationVectorBodyCoords == 0 ) == false )
    %{--------------------------------------------------------------------------
    %  The current rotation vector is not the zero vector.
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %  Update the handles involved.
    %---------------------------------------------------------------------------
       updatedTransformationHandle = transformationHandle;
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       updatedAngularMomentumVectorPatchGraphicsHandle =                     ...
                             angularMomentumVectorPatchGraphicsHandle;
       updatedAngularMomentumVectorLabelTextBoxHandle  =                     ...
                             angularMomentumVectorLabelTextBoxHandle;
       updatedAngularVelocityVectorPatchGraphicsHandle =                     ...
                             angularVelocityVectorPatchGraphicsHandle;
       updatedAngularVelocityVectorLabelTextBoxHandle  =                     ...
                             angularVelocityVectorLabelTextBoxHandle;
    %---------------------------------------------------------------------------
       currentRotationAngleRadians    = norm( currentRotationVectorBodyCoords );
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       oneRevolution                  = 2.0 * pi;
       currentRotationAngleRadiansMod = mod(                                 ...
                                             currentRotationAngleRadians,    ...
                                             oneRevolution                   ...
                                           );
    %---------------------------------------------------------------------------
    %  Obtain the rotation axis unit vector.
    %---------------------------------------------------------------------------
       currentRotationAxisUnitVector = currentRotationVectorBodyCoords /     ...
                                       currentRotationAngleRadians;
    %---------------------------------------------------------------------------
    %  Given a unit rotation axis and a rotation angle in radians,
    %  use the Matlab function 'makehgtform' to generate the 4 by 4
    %  transform matrix which performs the specified body coordinates
    %  to inertial coordinates transform operation with no translation.
    %---------------------------------------------------------------------------
       [                                                                     ...
         bodyToInertialCoordinatesTransformMatrix                            ...
       ] = makehgtform                                                       ...
               (                                                             ...
                 'AxisRotate',                                               ...
                 currentRotationAxisUnitVector,                              ...
                 currentRotationAngleRadiansMod                              ...
               );
    %---------------------------------------------------------------------------
    %
    %  Invoke the transform:
    %
    %    [ 1 ] From non-inertial body coordinates.
    %    [ 2 ] To       inertial      coordinates.
    %    [ 3 ] With     no       translation.
    %
    %  All graphics elements involved in the "updatedTransformationHandle"
    %  will be transformed from non-inertial body coordinates to
    %  inertial coordinates (with no translation of the center of gravity).
    %
    %---------------------------------------------------------------------------
       set                                                                   ...
        (                                                                    ...
          updatedTransformationHandle,                                       ...
          'Matrix',         bodyToInertialCoordinatesTransformMatrix         ...
        );
    %===========================================================================
    %
    %  Create a new Angular Velocity Vector at the updated inertial
    %  coordinates:
    %
    %===========================================================================
       specifiedFont                      = 'Helvetica';
       specifiedFontSize                  = 12;
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       currentAngularVelocityDirInertialCoord =                              ...
                     1.0 *                                                   ...
                     (                                                       ...
                             currentAngularVelocityVectorInertialCoord    /  ...
                       norm( currentAngularVelocityVectorInertialCoord  )    ...
                     );
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       arrowColor                =  colors.Red;
       labelColor                =  colors.Red;
    %---------------------------------------------------------------------------
    %  Erase the previous angular velocity vector graphics entity.
    %---------------------------------------------------------------------------
             updatedAngularVelocityVectorPatchGraphicsHandle.Visible = 'Off';
             updatedAngularVelocityVectorLabelTextBoxHandle.Visible  = 'Off';
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       clear updatedAngularVelocityVectorPatchGraphicsHandle;
       clear updatedAngularVelocityVectorLabelTextBoxHandle;
    %---------------------------------------------------------------------------
    %  Create the current angular velocity vector graphics entity.
    %---------------------------------------------------------------------------
             updatedAngularVelocityVectorPatchGraphicsHandle         = [ ];
             updatedAngularVelocityVectorLabelTextBoxHandle          = [ ];
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       [                                                                     ...
         updatedAngularVelocityVectorPatchGraphicsHandle,                    ...
         updatedAngularVelocityVectorLabelTextBoxHandle                      ...
       ] = createAngularVelocityVector                                       ...
                 (                                                           ...
                   arrowColor,                                               ...
                   labelColor,                                               ...
                   referencePosition,                                        ...
                   currentAngularVelocityDirInertialCoord,                   ...
                   specifiedFont,                                            ...
                   specifiedFontSize                                         ...
                 );
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       updatedAngularVelocityVectorPatchGraphicsHandle.Visible = 'On';
       updatedAngularVelocityVectorLabelTextBoxHandle.Visible  = 'On';
    %===========================================================================
    %
    %  Create a new Angular Momentum Vector at the updated inertial
    %  coordinates:
    %
    %===========================================================================
       specifiedFont                      = 'Helvetica';
       specifiedFontSize                  = 12;
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       currentAngularMomentumDirInertialCoord =                              ...
                    1.0 *                                                    ...
                    (                                                        ...
                            currentAngularMomentumVectorInertialCoord   /    ...
                      norm( currentAngularMomentumVectorInertialCoord )      ...
                    );
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       arrowColor                =  colors.Blue;
       labelColor                =  colors.Blue;
    %---------------------------------------------------------------------------
    %  Erase the previous angular momentum vector graphics entity.
    %---------------------------------------------------------------------------
             updatedAngularMomentumVectorPatchGraphicsHandle.Visible = 'Off';
             updatedAngularMomentumVectorLabelTextBoxHandle.Visible  = 'Off';
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       clear updatedAngularMomentumVectorPatchGraphicsHandle;
       clear updatedAngularMomentumVectorLabelTextBoxHandle;
    %---------------------------------------------------------------------------
    %  Create the current angular momentum vector graphics entity.
    %---------------------------------------------------------------------------
             updatedAngularMomentumVectorPatchGraphicsHandle         = [ ];
             updatedAngularMomentumVectorLabelTextBoxHandle          = [ ];
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       [                                                                     ...
         updatedAngularMomentumVectorPatchGraphicsHandle,                    ...
         updatedAngularMomentumVectorLabelTextBoxHandle                      ...
       ] = createAngularMomentumVector                                       ...
                 (                                                           ...
                   arrowColor,                                               ...
                   labelColor,                                               ...
                   referencePosition,                                        ...
                   currentAngularMomentumDirInertialCoord,                   ...
                   specifiedFont,                                            ...
                   specifiedFontSize                                         ...
                 );
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       updatedAngularMomentumVectorPatchGraphicsHandle.Visible = 'On';
       updatedAngularMomentumVectorLabelTextBoxHandle.Visible  = 'On';
    %}--------------------------------------------------------------------------
   end;
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------

