function                                                                     ...
[                                                                            ...
  xBodyAxisVectorPatchGraphicsHandle,                                        ...
  xBodyAxisLabelHandle                                                       ...
] =                                                                          ...
createXBodyAxisVector                                                        ...
      (                                                                      ...
        arrowColor,                                                          ...
        labelColor,                                                          ...
        xAxisBodyVectorStartWCS,                                             ...
        xAxisBodyVectorEndWCS,                                               ...
        specifiedFont,                                                       ...
        specifiedFontSize                                                    ...
      )
%===============================================================================
%|
%| UNCLASSIFIED
%|
%|==============================================================================
%|
%| FUNCTION:
%|
%|   createXBodyAxisVector
%|
%| PURPOSE:
%|
%|   This function will create:
%|     [ 1 ] A graphics object containing the              specified
%|           X body axis arrow vector.
%|     [ 2 ] A graphics object containing the label of the specified
%|           X body axis arrow vector.
%|
%| INPUT(s):
%|
%|   arrowColor
%|     The color to be used for the X body axis arrow vector.
%|
%|   labelColor
%|     The color to be used for the X body axis arrow label.`
%|
%|   xAxisBodyVectorStartWCS
%|     The (x,y,z) inertial World Coordinates (WCS) of the start
%|     of the X body axis vector.
%|
%|   xAxisBodyVectorEndWCS
%|     The (x,y,z) inertial World Coordinates (WCS) of the end
%|     of the X body axis vector.
%|
%|   specifiedFontSize
%|     The font size  to be used for the X body axis arrow label.
%|
%|   specifiedFont
%|     The font style to be used for the X body axis arrow label.
%|
%| OUTPUT(s):
%|
%|   xBodyAxisVectorPatchGraphicsHandle
%|     The handle of the graphics object containing the specified
%|     X body axis vector.
%|
%|   xBodyAxisLabelHandle
%|     The handle of the graphics object containing the label for the
%|     specified X body axis vector.
%|
%|------------------------------------------------------------------------------
%|
%| USAGE:
%|
%|   [                                                 ...
%|     xBodyAxisVectorPatchGraphicsHandle,             ...
%|     xBodyAxisLabelHandle                            ...
%|   ] = createXBodyAxisVector                         ...
%|             (                                       ...
%|               arrowColor,                           ...
%|               labelColor,                           ...
%|               xAxisBodyVectorStartWCS,              ...
%|               xAxisBodyVectorEndWCS,                ...
%|               specifiedFontSize,                    ...
%|               specifiedFont                         ...
%|             );
%|
%|==============================================================================
%|
%| UNCLASSIFIED
%|
%===============================================================================

%===============================================================================
%        1         2         3         4         5         6         7         8
%2345678901234567890123456789012345678901234567890123456789012345678901234567890
%===============================================================================

%{------------------------------------------------------------------------------
   STDOUT = 1;
%-------------------------------------------------------------------------------
   expectedNumberInputArgs  = 6;
   expectedNumberOutputArgs = 2;

   actualNumberInputArgs    = nargin;
   actualNumberOutputArgs   = nargout;
%-------------------------------------------------------------------------------
%  Check number of input arguments.
%-------------------------------------------------------------------------------
   if( actualNumberInputArgs == expectedNumberInputArgs )
    %{--------------------------------------------------------------------------
    %  Encountered expected number of input arguments.
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %  Check number of output arguments.
    %---------------------------------------------------------------------------
       if( actualNumberOutputArgs == expectedNumberOutputArgs )
        %{----------------------------------------------------------------------
        %  Encountered expected number of input arguments.
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        %  Obtain color definitions.
        %-----------------------------------------------------------------------
           colorDefinitions;
        %-----------------------------------------------------------------------
        %  Create a graphics object containing a two dimensional representation
        %  of the specified three dimensional X body axis arrow vector.
        %-----------------------------------------------------------------------
           X        = 1;
           Y        = 2;
           Z        = 3;
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           xBodyAxisUnitVector =       xAxisBodyVectorEndWCS    /            ...
                                 norm( xAxisBodyVectorEndWCS );
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           xBodyAxisScaleFactor     = 0.9;
           xBodyAxisIndicatorVector = xBodyAxisScaleFactor *                 ...
                                      xBodyAxisUnitVector;
        %-----------------------------------------------------------------------
           xBodyAxisVectorPatchGraphicsHandle = [ ];
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           [                                                                 ...
             xBodyAxisVectorPatchGraphicsHandle                              ...
           ] = mArrow3Create                                                 ...
                 (                                                           ...
                    xAxisBodyVectorStartWCS,                                 ...
                    xAxisBodyVectorEndWCS,                                   ...
                    'Color',            arrowColor                           ...
                 );
        %-----------------------------------------------------------------------
        %  Create a graphics object containing a two dimensional representation
        %  of the label for specified three dimensional X body axis arrow
        %  vector.
        %-----------------------------------------------------------------------
           [                                                                 ...
             xBodyAxisLabelString                                            ...
           ] = sprintf                                                       ...
                (                                                            ...
                  '%s',                                                      ...
                  ' X_{Body}'                                                ...
                );
           xBodyAxisLabelHandle = [ ];
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           [                                                                 ...
             xBodyAxisLabelHandle                                            ...
           ] = text                                                          ...
                (                                                            ...
                  xBodyAxisIndicatorVector( X ),                             ...
                  xBodyAxisIndicatorVector( Y ),                             ...
                  xBodyAxisIndicatorVector( Z ),                             ...
                  xBodyAxisLabelString,                                      ...
                  'FontName',                  specifiedFont,                ...
                  'FontSize',                  specifiedFontSize,            ...
                  'FontWeight',                'Bold',                       ...
                  'Color',                     labelColor                    ...
                );
        %}----------------------------------------------------------------------
       else
        %{----------------------------------------------------------------------
        %  Encountered unexpected number of output arguments.
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        %  This is an error.
        %  Generate a  purpose message.
        %-----------------------------------------------------------------------
           [                                                                 ...
             purposeMessageString                                            ...
           ] = generatePurposeMessage(  );
        %-----------------------------------------------------------------------
        %  Generate an usage   message.
        %-----------------------------------------------------------------------
           [                                                                 ...
             usageMessageString                                              ...
           ] = generateUsageMessage(  );
        %-----------------------------------------------------------------------
        %  Output a  purpose message.
        %-----------------------------------------------------------------------
           fprintf                                                           ...
             (                                                               ...
               STDOUT,                                                       ...
               '%s',                                                         ...
               purposeMessageString                                          ...
             );
        %-----------------------------------------------------------------------
        %  Output an usage   message.
        %-----------------------------------------------------------------------
           fprintf                                                           ...
             (                                                               ...
               STDOUT,                                                       ...
               '%s',                                                         ...
               usageMessageString                                            ...
             );
        %-----------------------------------------------------------------------
        %  Generate an error message.
        %-----------------------------------------------------------------------
           errorMessageFormattingString =                                    ...
                [                                                            ...
                  '\n\n\n'                                                   ...
                  '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                         ...
                  '%s%d\n'                                                   ...
                  '%s%d\n'                                                   ...
                  '%s\n%s\n%s\n%s\n%s\n'                                     ...
                  '\n\n\n'                                                   ...
                ];
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           fprintf                                                           ...
           (                                                                 ...
             STDOUT,                                                         ...
             errorMessageFormattingString,                                   ...
             '------------------------------------------------------------', ...
             '|',                                                            ...
             '| ERROR:',                                                     ...
             '|',                                                            ...
             '|   Function "createXBodyAxisVector":',                        ...
             '|',                                                            ...
             '|   Encountered unexpected number of output arguments.',       ...
             '|',                                                            ...
             '|   Expected number output arguments:-->',                     ...
             expectedNumberOutputArgs,                                       ...
             '|   Actual   number output arguments:-->',                     ...
             actualNumberOutputArgs,                                         ...
             '|',                                                            ...
             '|  This is an error.',                                         ...
             '|  The program will terminate.',                               ...
             '|',                                                            ...
             '------------------------------------------------------------'  ...
            );
        %-----------------------------------------------------------------------
           xBodyAxisVectorPatchGraphicsHandle = [ ];
           xBodyAxisLabelHandle               = [ ];
        %-----------------------------------------------------------------------
        %  Terminate the program.
        %-----------------------------------------------------------------------
           error( 'Encountered unexpected number of output arguments.' );
        %}----------------------------------------------------------------------
       end;
    %}--------------------------------------------------------------------------
   else
    %{--------------------------------------------------------------------------
    %  Encountered unexpected number of input arguments.
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %  This is an error.
    %  Generate a  purpose message.
    %---------------------------------------------------------------------------
       [                                                                     ...
         purposeMessageString                                                ...
       ] = generatePurposeMessage(  );
    %---------------------------------------------------------------------------
    %  Generate an usage   message.
    %---------------------------------------------------------------------------
       [                                                                     ...
         usageMessageString                                                  ...
       ] = generateUsageMessage(  );
    %---------------------------------------------------------------------------
    %  Output a  purpose message.
    %---------------------------------------------------------------------------
       fprintf                                                               ...
         (                                                                   ...
           STDOUT,                                                           ...
           '%s',                                                             ...
           purposeMessageString                                              ...
         );
    %---------------------------------------------------------------------------
    %  Output an usage   message.
    %---------------------------------------------------------------------------
       fprintf                                                               ...
         (                                                                   ...
           STDOUT,                                                           ...
           '%s',                                                             ...
           usageMessageString                                                ...
         );
    %---------------------------------------------------------------------------
    %  Generate an error message.
    %---------------------------------------------------------------------------
       errorMessageFormattingString =                                        ...
            [                                                                ...
              '\n\n\n'                                                       ...
              '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                             ...
              '%s%d\n'                                                       ...
              '%s%d\n'                                                       ...
              '%s\n%s\n%s\n%s\n%s\n'                                         ...
              '\n\n\n'                                                       ...
            ];
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       fprintf                                                               ...
       (                                                                     ...
         STDOUT,                                                             ...
         errorMessageFormattingString,                                       ...
         '----------------------------------------------------------------', ...
         '|',                                                                ...
         '| ERROR:',                                                         ...
         '|',                                                                ...
         '|   Function "createXBodyAxisVector":',                            ...
         '|',                                                                ...
         '|   Encountered unexpected number of input arguments.',            ...
         '|',                                                                ...
         '|   Expected number input  arguments:-->',                         ...
         expectedNumberInputArgs,                                            ...
         '|   Actual   number input  arguments:-->',                         ...
         actualNumberInputArgs,                                              ...
         '|',                                                                ...
         '|  This is an error.',                                             ...
         '|  The program will terminate.',                                   ...
         '|',                                                                ...
         '----------------------------------------------------------------'  ...
       );
    %---------------------------------------------------------------------------
       xBodyAxisVectorPatchGraphicsHandle = [ ];
       xBodyAxisLabelHandle               = [ ];
    %---------------------------------------------------------------------------
    %  Terminate the program.
    %---------------------------------------------------------------------------
       error( 'Encountered unexpected number of input arguments.' );
    %}--------------------------------------------------------------------------
   end;
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
function                                                                     ...
[                                                                            ...
  purposeMessageString                                                       ...
] =                                                                          ...
generatePurposeMessage(  )
%{------------------------------------------------------------------------------
   purposeMessageFormattingString =                                          ...
          [                                                                  ...
            '\n\n\n',                                                        ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                                   ...
            '\n\n\n'                                                         ...
          ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     purposeMessageString                                                    ...
   ] =                                                                       ...
    sprintf                                                                  ...
     (                                                                       ...
       purposeMessageFormattingString,                                       ...
       '==================================================================', ...
       '|',                                                                  ...
       '| UNCLASSIFIED',                                                     ...
       '|',                                                                  ...
       '|=================================================================', ...
       '|',                                                                  ...
       '| FUNCTION:',                                                        ...
       '|',                                                                  ...
       '|   createXBodyAxisVector',                                          ...
       '|',                                                                  ...
       '| PURPOSE:',                                                         ...
       '|',                                                                  ...
       '|   This function will create:',                                     ...
       '|     [ 1 ] A graphics object containing the X body axis',           ...
       '|           vector.',                                                ...
       '|     [ 2 ] A graphics object containing the label of the X body',   ...
       '|           axis vector.',                                           ...
       '|',                                                                  ...
       '| INPUT(s):',                                                        ...
       '|',                                                                  ...
       '|   arrowColor',                                                     ...
       '|     The color to be used for the X body axis vector arrow',        ...
       '|',                                                                  ...
       '|   labelColor',                                                     ...
       '|     The color to be used for the X body axis vecor arrow label.',  ...
       '|',                                                                  ...
       '|   xAxisBodyVectorStartWCS',                                        ...
       '|     The (x,y,z) inertial World Coordinates (WCS) of the',          ...
       '|     start of the X body axis vector.',                             ...
       '|',                                                                  ...
       '|   xAxisBodyVectorEndWCS',                                          ...
       '|     The (x,y,z) inertial World Coordinates (WCS) of the end',      ...
       '|     of the X body axis vector.',                                   ...
       '|',                                                                  ...
       '|   specifiedFontSize',                                              ...
       '|     The font size to be used for the X body axis vector arrow',    ...
       '|     label.',                                                       ...
       '|',                                                                  ...
       '|   specifiedFont',                                                  ...
       '|     The font style to be used for the X body axis vector arrow',   ...
       '|     label.',                                                       ...
       '|',                                                                  ...
       '| OUTPUT(s):',                                                       ...
       '|',                                                                  ...
       '|   xBodyAxisVectorPatchGraphicsHandle',                             ...
       '|     The handle of the patch graphics object containing the',       ...
       '|     X body axis vector.',                                          ...
       '|',                                                                  ...
       '|   xBodyAxisLabelHandle',                                           ...
       '|     The handle of the graphics object containing the label for',   ...
       '|     the X body axis vector.',                                      ...
       '|',                                                                  ...
       '|=================================================================', ...
       '|',                                                                  ...
       '| UNCLASSIFIED',                                                     ...
       '|',                                                                  ...
       '=================================================================='  ...
     );
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
function                                                                     ...
[                                                                            ...
  usageMessageString                                                         ...
] =                                                                          ...
generateUsageMessage(  )
%{------------------------------------------------------------------------------
   usageMessageFormattingString =                                            ...
        [                                                                    ...
          '\n\n\n'                                                           ...
          '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                         ...
          '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                                 ...
          '\n\n\n'                                                           ...
        ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     usageMessageString                                                      ...
   ] =                                                                       ...
    sprintf                                                                  ...
     (                                                                       ...
       usageMessageFormattingString,                                         ...
       '----------------------------------------------------------------',   ...
       '|',                                                                  ...
       '| USAGE:',                                                           ...
       '|',                                                                  ...
       '|   [                                                 ...',          ...
       '|     xBodyAxisVectorPatchGraphicsHandle,             ...',          ...
       '|     xBodyAxisLabelHandle                            ...',          ...
       '|   ] = createXBodyAxisVector                         ...',          ...
       '|             (                                       ...',          ...
       '|               arrowColor,                           ...',          ...
       '|               labelColor,                           ...',          ...
       '|               xAxisBodyVectorStartWCS,              ...',          ...
       '|               xAxisBodyVectorEndWCS,                ...',          ...
       '|               specifiedFontSize,                    ...',          ...
       '|               specifiedFont                         ...',          ...
       '|             );',                                                   ...
       '|',                                                                  ...
       '----------------------------------------------------------------'    ...
     );
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
%
%  UNCLASSIFIED
%
%===============================================================================
