function                                                                     ...
[                                                                            ...
  angularMomentumVectorPatchGraphicsHandle,                                  ...
  angularMomentumLabelHandle                                                 ...
] =                                                                          ...
createAngularMomentumVector                                                  ...
      (                                                                      ...
        arrowColor,                                                          ...
        labelColor,                                                          ...
        initialReferencePosition,                                            ...
        angularMomentumVectorEndCoordinates,                                 ...
        specifiedFont,                                                       ...
        specifiedFontSize                                                    ...
      )
%===============================================================================
%|
%| UNCLASSIFIED
%|
%|==============================================================================
%|
%| FUNCTION:
%|
%|   createAngularMomentumVector
%|
%| PURPOSE:
%|
%|   This function will create:
%|     [ 1 ] A graphics object containing the              specified
%|           angular momentum arrow vector.
%|     [ 2 ] A graphics object containing the label of the specified
%|           angular momentum arrow vector.
%|
%| INPUT(s):
%|
%|   arrowColor
%|     The color to be used for the angular momentum arrow vector.
%|
%|   labelColor
%|     The color to be used for the angular momentum label.
%|
%|   initialReferencePosition
%|     The inertial World Coordinate System (WCS) coordinates of the
%|     origin of the Body Coordinate System (BCS).
%|
%|   angularMomentumVectorEndCoordinates
%|     The (x,y,z) coordinates of the end of the angular momentum
%|     vector.
%|
%|   specifiedFontSize
%|     The font size to be used for the x body axis arrow label.
%|
%|   specifiedFont
%|     The font style to be used for the x body axis arrow label.
%|
%| OUTPUT(s):
%|
%|   angularMomentumVectorPatchGraphicsHandle
%|     The handle of the graphics object containing the specified
%|     angular momentum vector.
%|
%|   angularMomentumLabelHandle
%|     The handle of the graphics object containing the label for the
%|     specified angular momentum vector.
%|
%|------------------------------------------------------------------------------
%|
%| USAGE:
%|
%|   [                                                 ...
%|     angularMomentumVectorPatchGraphicsHandle,       ...
%|     angularMomentumLabelHandle                      ...
%|   ] = createAngularMomentumVector                   ...
%|             (                                       ...
%|               arrowColor,                           ...
%|               labelColor,                           ...
%|               initialReferencePosition,             ...
%|               angularMomentumVectorEndCoordinates,  ...
%|               specifiedFontSize,                    ...
%|               specifiedFont                         ...
%|             );
%|
%|==============================================================================
%|
%| UNCLASSIFIED
%|
%===============================================================================

%===============================================================================
%        1         2         3         4         5         6         7         8
%2345678901234567890123456789012345678901234567890123456789012345678901234567890
%===============================================================================

%{------------------------------------------------------------------------------
   STDOUT = 1;
%-------------------------------------------------------------------------------
   expectedNumberInputArgs  = 6;
   expectedNumberOutputArgs = 2;

   actualNumberInputArgs    = nargin;
   actualNumberOutputArgs   = nargout;
%-------------------------------------------------------------------------------
%  Check number of input arguments.
%-------------------------------------------------------------------------------
   if( actualNumberInputArgs == expectedNumberInputArgs )
    %{--------------------------------------------------------------------------
    %  Encountered expected number of input arguments.
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %  Check number of output arguments.
    %---------------------------------------------------------------------------
       if( actualNumberOutputArgs == expectedNumberOutputArgs )
        %{----------------------------------------------------------------------
        %  Encountered expected number of input arguments.
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        %  Obtain color definitions.
        %-----------------------------------------------------------------------
           colorDefinitions;
        %-----------------------------------------------------------------------
        %  Create a graphics object containing a two dimensional representation
        %  of the specified three dimensional angular momentum arrow vector.
        %-----------------------------------------------------------------------
           X        = 1;
           Y        = 2;
           Z        = 3;
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           angularMomentumUnitVector =                                       ...
                                    angularMomentumVectorEndCoordinates    / ...
                              norm( angularMomentumVectorEndCoordinates );
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           angularMomentumScaleFactor = 0.9;
           angularMomentumIndicatorVector = angularMomentumScaleFactor *     ...
                                            angularMomentumUnitVector;
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           arrowStop3D  = initialReferencePosition +                         ...
                          [                                                  ...
                            angularMomentumIndicatorVector( X );             ...
                            angularMomentumIndicatorVector( Y );             ...
                            angularMomentumIndicatorVector( Z )              ...
                          ];
        %-----------------------------------------------------------------------
           angularMomentumVectorPatchGraphicsHandle = [ ];
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           [                                                                 ...
             angularMomentumVectorPatchGraphicsHandle                        ...
           ] = mArrow3Create                                                 ...
                (                                                            ...
                   initialReferencePosition,                                 ...
                   arrowStop3D,                                              ...
                   'Color',            arrowColor                            ...
                );
        %-----------------------------------------------------------------------
        %  Create a graphics object containing a two dimensional representation
        %  of the label for specified three dimensional angular momentum arrow
        %  vector.
        %-----------------------------------------------------------------------
           angularMomentumLabelString = ' L';
           angularMomentumLabelHandle = [ ];
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           [                                                                 ...
             angularMomentumLabelHandle                                      ...
           ] = text                                                          ...
                (                                                            ...
                  arrowStop3D( X ),                                          ...
                  arrowStop3D( Y ),                                          ...
                  arrowStop3D( Z ),                                          ...
                  angularMomentumLabelString,                                ...
                  'FontName',                  'Helvetica',                  ...
                  'FontSize',                  18,                           ...
                  'FontWeight',                'Bold',                       ...
                  'Color',                     labelColor                    ...
                );
        %}----------------------------------------------------------------------
       else
        %{----------------------------------------------------------------------
        %  Encountered unexpected number of output arguments.
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
        %  This is an error.
        %  Generate a  purpose message.
        %-----------------------------------------------------------------------
           [                                                                 ...
             purposeMessageString                                            ...
           ] = generatePurposeMessage(  );
        %-----------------------------------------------------------------------
        %  Generate an usage   message.
        %-----------------------------------------------------------------------
           [                                                                 ...
             usageMessageString                                              ...
           ] = generateUsageMessage(  );
        %-----------------------------------------------------------------------
        %  Output a  purpose message.
        %-----------------------------------------------------------------------
           fprintf                                                           ...
             (                                                               ...
               STDOUT,                                                       ...
               '%s',                                                         ...
               purposeMessageString                                          ...
             );
        %-----------------------------------------------------------------------
        %  Output an usage   message.
        %-----------------------------------------------------------------------
           fprintf                                                           ...
             (                                                               ...
               STDOUT,                                                       ...
               '%s',                                                         ...
               usageMessageString                                            ...
             );
        %-----------------------------------------------------------------------
        %  Generate an error message.
        %-----------------------------------------------------------------------
           errorMessageFormattingString =                                    ...
                [                                                            ...
                  '\n\n\n'                                                   ...
                  '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                         ...
                  '%s%d\n'                                                   ...
                  '%s%d\n'                                                   ...
                  '%s\n%s\n%s\n%s\n%s\n'                                     ...
                  '\n\n\n'                                                   ...
                ];
        %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
           fprintf                                                           ...
           (                                                                 ...
             STDOUT,                                                         ...
             errorMessageFormattingString,                                   ...
             '------------------------------------------------------------', ...
             '|',                                                            ...
             '| ERROR:',                                                     ...
             '|',                                                            ...
             '|   Function "createAngularMomentumVector":',                  ...
             '|',                                                            ...
             '|   Encountered unexpected number of output arguments.',       ...
             '|',                                                            ...
             '|   Expected number output arguments:-->',                     ...
             expectedNumberOutputArgs,                                       ...
             '|   Actual   number output arguments:-->',                     ...
             actualNumberOutputArgs,                                         ...
             '|',                                                            ...
             '|  This is an error.',                                         ...
             '|  The program will terminate.',                               ...
             '|',                                                            ...
             '------------------------------------------------------------'  ...
            );
        %-----------------------------------------------------------------------
           angularMomentumVectorPatchGraphicsHandle = [ ];
           angularMomentumLabelHandle               = [ ];
        %-----------------------------------------------------------------------
        %  Terminate the program.
        %-----------------------------------------------------------------------
           error( 'Encountered unexpected number of output arguments.' );
        %}----------------------------------------------------------------------
       end;
    %}--------------------------------------------------------------------------
   else
    %{--------------------------------------------------------------------------
    %  Encountered unexpected number of input arguments.
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    %  This is an error.
    %  Generate a  purpose message.
    %---------------------------------------------------------------------------
       [                                                                     ...
         purposeMessageString                                                ...
       ] = generatePurposeMessage(  );
    %---------------------------------------------------------------------------
    %  Generate an usage   message.
    %---------------------------------------------------------------------------
       [                                                                     ...
         usageMessageString                                                  ...
       ] = generateUsageMessage(  );
    %---------------------------------------------------------------------------
    %  Output a  purpose message.
    %---------------------------------------------------------------------------
       fprintf                                                               ...
         (                                                                   ...
           STDOUT,                                                           ...
           '%s',                                                             ...
           purposeMessageString                                              ...
         );
    %---------------------------------------------------------------------------
    %  Output an usage   message.
    %---------------------------------------------------------------------------
       fprintf                                                               ...
         (                                                                   ...
           STDOUT,                                                           ...
           '%s',                                                             ...
           usageMessageString                                                ...
         );
    %---------------------------------------------------------------------------
    %  Generate an error message.
    %---------------------------------------------------------------------------
       errorMessageFormattingString =                                        ...
            [                                                                ...
              '\n\n\n'                                                       ...
              '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                             ...
              '%s%d\n'                                                       ...
              '%s%d\n'                                                       ...
              '%s\n%s\n%s\n%s\n%s\n'                                         ...
              '\n\n\n'                                                       ...
            ];
    %- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
       fprintf                                                               ...
       (                                                                     ...
         STDOUT,                                                             ...
         errorMessageFormattingString,                                       ...
         '----------------------------------------------------------------', ...
         '|',                                                                ...
         '| ERROR:',                                                         ...
         '|',                                                                ...
         '|   Function "createAngularMomentumVector":',                      ...
         '|',                                                                ...
         '|   Encountered unexpected number of input arguments.',            ...
         '|',                                                                ...
         '|   Expected number input  arguments:-->',                         ...
         expectedNumberInputArgs,                                            ...
         '|   Actual   number input  arguments:-->',                         ...
         actualNumberInputArgs,                                              ...
         '|',                                                                ...
         '|  This is an error.',                                             ...
         '|  The program will terminate.',                                   ...
         '|',                                                                ...
         '----------------------------------------------------------------'  ...
       );
    %---------------------------------------------------------------------------
       angularMomentumVectorPatchGraphicsHandle = [ ];
       angularMomentumLabelHandle               = [ ];
    %---------------------------------------------------------------------------
    %  Terminate the program.
    %---------------------------------------------------------------------------
       error( 'Encountered unexpected number of input arguments.' );
    %}--------------------------------------------------------------------------
   end;
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
function                                                                     ...
[                                                                            ...
  purposeMessageString                                                       ...
] =                                                                          ...
generatePurposeMessage(  )
%{------------------------------------------------------------------------------
   purposeMessageFormattingString =                                          ...
          [                                                                  ...
            '\n\n\n',                                                        ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                       ...
            '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                           ...
            '\n\n\n'                                                         ...
          ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     purposeMessageString                                                    ...
   ] =                                                                       ...
    sprintf                                                                  ...
     (                                                                       ...
       purposeMessageFormattingString,                                       ...
       '==================================================================', ...
       '|',                                                                  ...
       '| UNCLASSIFIED',                                                     ...
       '|',                                                                  ...
       '|=================================================================', ...
       '|',                                                                  ...
       '| FUNCTION:',                                                        ...
       '|',                                                                  ...
       '|   createAngularMomentumVector',                                    ...
       '|',                                                                  ...
       '| PURPOSE:',                                                         ...
       '|',                                                                  ...
       '|   This function will create:',                                     ...
       '|     [ 1 ] A graphics object containing the angular momentum',      ...
       '|           vector.',                                                ...
       '|     [ 2 ] A graphics object containing the label of the angular',  ...
       '|           momentum vector.',                                       ...
       '|',                                                                  ...
       '| INPUT(s):',                                                        ...
       '|',                                                                  ...
       '|   arrowColor',                                                     ...
       '|     The color to be used for the angular momentum vector',         ...
       '|     arrow.',                                                       ...
       '|',                                                                  ...
       '|   labelColor',                                                     ...
       '|     The color to be used for the angular momentum vector',         ...
       '|     label.',                                                       ...
       '|',                                                                  ...
       '|   initialReferencePosition',                                       ...
       '|     The inertial World Coordinate System (WCS) coordinates of',    ...
       '|     the origin of the Body Coordinate System (BCS).',              ...
       '|',                                                                  ...
       '|   angularMomentumVectorEndCoordinates',                            ...
       '|     The (x,y,z) coordinates of the end of the angular momentum',   ...
       '|     arrow vector.',                                                ...
       '|',                                                                  ...
       '|   specifiedFontSize',                                              ...
       '|     The font size to be used for the angular momentum arrow',      ...
       '|     label.',                                                       ...
       '|',                                                                  ...
       '|   specifiedFont',                                                  ...
       '|     The font style to be used for the angular momentum arrow',     ...
       '|     label.',                                                       ...
       '|',                                                                  ...
       '| OUTPUT(s):',                                                       ...
       '|',                                                                  ...
       '|   angularMomentumVectorPatchGraphicsHandle',                       ...
       '|     The handle of the patch graphics object containing the',       ...
       '|     angular momentum vector.',                                     ...
       '|',                                                                  ...
       '|   angularMomentumLabelHandle',                                     ...
       '|     The handle of the graphics object containing the label for',   ...
       '|     the angular momentum vector.',                                 ...
       '|',                                                                  ...
       '|=================================================================', ...
       '|',                                                                  ...
       '| UNCLASSIFIED',                                                     ...
       '|',                                                                  ...
       '=================================================================='  ...
     );
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
function                                                                     ...
[                                                                            ...
  usageMessageString                                                         ...
] =                                                                          ...
generateUsageMessage(  )
%{------------------------------------------------------------------------------
   usageMessageFormattingString =                                            ...
        [                                                                    ...
          '\n\n\n'                                                           ...
          '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                         ...
          '%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n'                                 ...
          '\n\n\n'                                                           ...
        ];
%- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
   [                                                                         ...
     usageMessageString                                                      ...
   ] =                                                                       ...
    sprintf                                                                  ...
     (                                                                       ...
       usageMessageFormattingString,                                         ...
       '----------------------------------------------------------------',   ...
       '|',                                                                  ...
       '| USAGE:',                                                           ...
       '|',                                                                  ...
       '|   [                                                 ...',          ...
       '|     angularMomentumVectorPatchGraphicsHandle,       ...',          ...
       '|     angularMomentumLabelHandle                      ...',          ...
       '|   ] = createAngularMomentumVector                   ...',          ...
       '|             (                                       ...',          ...
       '|               arrowColor,                           ...',          ...
       '|               labelColor,                           ...',          ...
       '|               initialReferencePosition,             ...',          ...
       '|               angularMomentumVectorEndCoordinates,  ...',          ...
       '|               specifiedFontSize,                    ...',          ...
       '|               specifiedFont                         ...',          ...
       '|             );',                                                   ...
       '|',                                                                  ...
       '----------------------------------------------------------------'    ...
     );
%-------------------------------------------------------------------------------
   return;
%}------------------------------------------------------------------------------


%===============================================================================
%
%  UNCLASSIFIED
%
%===============================================================================
